version: "3"
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./db/mongo:/data/db
    ports:
      - "27017:27017"
